// <auto-generated />
namespace ElecWarSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class timeSended : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(timeSended));
        
        string IMigrationMetadata.Id
        {
            get { return "202301171624465_timeSended"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
